### ISSUE TITLE
The automatic time changeover from winter time to summer time takes place approx. 2 weeks too early

### ISSUE THREAD

**Issue by tglion** [contrem/arduino-timer#89]
On my ESP32 I configure with configTime(3600, 3600, "time.google.com"); European Time for Germany(MESZ) with automatic time changeover. I have the issue, that the automatic time changeover from winter time to summer time takes place approx. 2 weeks too early. It seems that he uses the American dates for the summer/winter time changeover and not the European ones? How can I fix this?

**Comment by philj404** [comment]
`configTime()` is not part of this library.

I think your issue is unrelated to this library.  Arduino-timer by default only works with "milliseconds elapsed since reset", so does not support any outside time references like "time.google.com".  

It doesn't care what the local time zone may be, whether it's "daylight" or "standard" time -- or even what the current year is.

Is `configTime()` part of an ESP32 library?
